version: '3'

services:
  master1:
    image: chrislusf/seaweedfs
    ports:
      - 13330:13330
    volumes:
      - ./master1:/data
    command: 'master -port=13330 -ip.bind="0.0.0.0" -peers=master1:13330,master2:13332,master3:13334'
    networks:
      - 'weednet'
  master2:
    image: chrislusf/seaweedfs
    ports:
      - 13332:13332
    volumes:
      - ./master2:/data
    command: 'master -port=13332 -ip.bind="0.0.0.0" -peers=master1:13330,master2:13332,master3:13334'
    depends_on:
      - master1
    networks:
      - 'weednet'
  master3:
    image: chrislusf/seaweedfs
    ports:
      - 13334:13334
    volumes:
      - ./master3:/data
    command: 'master -port=13334 -ip.bind="0.0.0.0" -peers=master1:13330,master2:13332,master3:13334'
    depends_on:
      - master2
    networks:
      - 'weednet'

  haproxy1:
    image: haproxy:latest
    ports:
      - 80:80
    volumes:
      - ./haproxy1:/usr/local/etc/haproxy
    links:
      - master1
      - master2
      - master3
    networks:
      - 'weednet'

  volume1:
    image: chrislusf/seaweedfs
    ports:
      - 16310:8080
    volumes:
      - ./data1:/data
    command: 'volume -max=5 -port=8080  -ip.bind="0.0.0.0" -mserver=master1:9333'
    depends_on:
      - master1
      - master2
      - master3
    links:
      - master1
      - master2
      - master3
    networks:
      - 'weednet'
  volume2:
    image: chrislusf/seaweedfs
    ports:
      - 16312:8081
    volumes:
      - ./data2:/data
    command: 'volume -max=5 -port=8081  -ip.bind="0.0.0.0" -mserver=master1:13330'
    depends_on:
      - master1
      - master2
      - master3
    links:
      - master1
      - master2
      - master3
    networks:
      - 'weednet'
  volume3:
    image: chrislusf/seaweedfs
    ports:
      - 16314:8082
    volumes:
      - ./data3:/data
    command: 'volume -max=5 -port=8082  -ip.bind="0.0.0.0" -mserver=master1:13330'
    depends_on:
      - master1
      - master2
      - master3
    links:
      - master1
      - master2
      - master3
    networks:
      - 'weednet'
  volume4:
    image: chrislusf/seaweedfs
    ports:
      - 16316:8083
    volumes:
      - ./data4:/data
    command: 'volume -max=5 -port=8083  -ip.bind="0.0.0.0" -mserver=master1:13330'
    depends_on:
      - master1
      - master2
      - master3
    links:
      - master1
      - master2
      - master3
    networks:
      - 'weednet'

networks:
  weednet:
    driver: bridge # 桥接网络
